import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
 
export const viewport: Viewport = {
  colorScheme: 'light',
}
 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex justify-center py-32">
          {children}
        </main>
      </body>
    </html>
  );
}
